### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by gdh1995** [gdh1995/vimium-c#13]
- [x] influence of sandboxed page (e.g. https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/contrib/android/cmake/src/main/AndroidManifest.xml)
- [x] Vomnibar: use a char of `...` to replace 3 `.`s
- [x] FindMode: whole-word finding

### v1.74 / v1.75

- [x] option to open newtab in current
- [x] exclusion option: line cache
- [x] scroll step limit
- [x] vomnibar wheel on end
- [x] linkhint: optional touch events
- [x] - https://www.html5rocks.com/en/mobile/touchandmouse/
- ~click ignore dialog::backdrop~

### Long term tasks
- [x] ? why initing might stop since exclusions.js (has not been reproduced recently)
- [x] ? handle `mapKey * <esc>`
- [ ] ? support -webkit-user-modify: *write*
- [x] use some cache during VHints.traverse
- [ ] auto find text and make hints (like `<v>` in `VimFx`) ( #3 )
- [x] use `chrome.storage` to ~~store local settings~~ sync settings
- [x] implement filtered hints ( #23 )
- [x] translate into Chinese
  - [x] translate options.html
  - [x] translate help_dialog.html
- [ ] write wiki...
- [x] rework FindMode's exit logic 

- Firefox / Edge
  - [x] basic running
  - [x] supports no Shadow DOM
  - [x] `moz-*` schemas
  - [x] tabs.query does not support `moz-extension://$id/pages/options.html`
  - [x] ~~no `browser.windows`~~
  - [x] clipboard problem
  - [x] wrap around in FindMode

- [x] ~~? merge from mrmr1995: Render for Hints~~ (given up)
- [x] visual viewport
  - [x] Hints.getElementsInViewPort: need visualViewport.height
  - [x] Scroller: use visualViewport.height / .width (impossible on 2019/10/04)
  - [x] DomUtils: prepareCrop, getViewBox, ensureInView, setBoundary

### From Dark Magician

- [ ] multiple keywords on Vomnibar and vimium://parse
- [x] search engine's special URL for empty queries
- [x] advanced usages of custom CSS
- [ ] custom suggestion
- [x] Hint to cursor
- [ ] Hint of page text (like VimFx)
- [x] helpful hints in help dialog
- [x] 99 times and the confirm dialog
  - [x] reloadTab
  - [x] if the dialog disabled, fallback into running command once

**Comment by gdh1995** [comment]
Closed - Most left tasks have been out-of-date (except `v`  in VimFx).
